package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "bill")
public class Bill implements java.io.Serializable {

	private int billId;
	private Event event;
	private Date billDate;
	private String partyName;
	private String debitNote;
	private int invoiceNo;
	private int serviceTax;
	private int amount;
	public int getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	private int grandTotal;
	private String status;
	
	

	public Bill() {
	}

	public Bill(int billId, Event event, String partyName, String debitNote,
			int invoiceNo, int serviceTax, int grandTotal,int amount) {
		this.billId = billId;
		this.event = event;
		this.partyName = partyName;
		this.debitNote = debitNote;
		this.invoiceNo = invoiceNo;
		this.serviceTax = serviceTax;
		this.grandTotal = grandTotal;
		this.amount=amount;
	}

	public Bill(int billId, Event event, Date billDate, String partyName,
			String debitNote, int invoiceNo, int serviceTax, int grandTotal,
			String status,int amount) {
		this.billId = billId;
		this.event = event;
		this.billDate = billDate;
		this.partyName = partyName;
		this.debitNote = debitNote;
		this.invoiceNo = invoiceNo;
		this.serviceTax = serviceTax;
		this.grandTotal = grandTotal;
		this.status = status;
		this.amount=amount;
	}
	
	@Id
    @GenericGenerator(name = "generator", strategy = "increment")
    @GeneratedValue(generator = "generator")

	public int getBillId() {
		return this.billId;
	}

	public void setBillId(int billId) {
		this.billId = billId;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	public String getPartyName() {
		return this.partyName;
	}

	public void setPartyName(String partyName) {
		this.partyName = partyName;
	}

	public String getDebitNote() {
		return this.debitNote;
	}

	public void setDebitNote(String debitNote) {
		this.debitNote = debitNote;
	}

	public int getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(int invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	public int getServiceTax() {
		return this.serviceTax;
	}

	public void setServiceTax(int serviceTax) {
		this.serviceTax = serviceTax;
	}

	public int getGrandTotal() {
		return this.grandTotal;
	}

	public void setGrandTotal(int grandTotal) {
		this.grandTotal = grandTotal;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
