package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

/**
 * EventLicenseMapping generated by hbm2java
 */
public class EventLicenseMapping implements java.io.Serializable {

	private EventLicenseMappingId id;
	private Event event;
	private License license;

	public EventLicenseMapping() {
	}

	public EventLicenseMapping(EventLicenseMappingId id, Event event,
			License license) {
		this.id = id;
		this.event = event;
		this.license = license;
	}

	public EventLicenseMappingId getId() {
		return this.id;
	}

	public void setId(EventLicenseMappingId id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public License getLicense() {
		return this.license;
	}

	public void setLicense(License license) {
		this.license = license;
	}

}
