package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Event generated by hbm2java
 */
public class Event implements java.io.Serializable {

	private int eventId;
	private String eventName;
	private String comanyName;
	private Date date;
	private int contact;
	private String email;
	private Set bills = new HashSet(0);
	private Set userEventMappings = new HashSet(0);
	private Set eventLicenseMappings = new HashSet(0);

	public Event() {
	}

	public Event(int eventId, int contact) {
		this.eventId = eventId;
		this.contact = contact;
	}

	public Event(int eventId, String eventName, String comanyName, Date date,
			int contact, String email, Set bills, Set userEventMappings,
			Set eventLicenseMappings) {
		this.eventId = eventId;
		this.eventName = eventName;
		this.comanyName = comanyName;
		this.date = date;
		this.contact = contact;
		this.email = email;
		this.bills = bills;
		this.userEventMappings = userEventMappings;
		this.eventLicenseMappings = eventLicenseMappings;
	}

	public int getEventId() {
		return this.eventId;
	}

	public void setEventId(int eventId) {
		this.eventId = eventId;
	}

	public String getEventName() {
		return this.eventName;
	}

	public void setEventName(String eventName) {
		this.eventName = eventName;
	}

	public String getComanyName() {
		return this.comanyName;
	}

	public void setComanyName(String comanyName) {
		this.comanyName = comanyName;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getContact() {
		return this.contact;
	}

	public void setContact(int contact) {
		this.contact = contact;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getBills() {
		return this.bills;
	}

	public void setBills(Set bills) {
		this.bills = bills;
	}

	public Set getUserEventMappings() {
		return this.userEventMappings;
	}

	public void setUserEventMappings(Set userEventMappings) {
		this.userEventMappings = userEventMappings;
	}

	public Set getEventLicenseMappings() {
		return this.eventLicenseMappings;
	}

	public void setEventLicenseMappings(Set eventLicenseMappings) {
		this.eventLicenseMappings = eventLicenseMappings;
	}

}
