package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * License generated by hbm2java
 */
public class License implements java.io.Serializable {

	private int licenseId;
	private String licenseName;
	private Set eventLicenseMappings = new HashSet(0);

	public License() {
	}

	public License(int licenseId) {
		this.licenseId = licenseId;
	}

	public License(int licenseId, String licenseName, Set eventLicenseMappings) {
		this.licenseId = licenseId;
		this.licenseName = licenseName;
		this.eventLicenseMappings = eventLicenseMappings;
	}

	public int getLicenseId() {
		return this.licenseId;
	}

	public void setLicenseId(int licenseId) {
		this.licenseId = licenseId;
	}

	public String getLicenseName() {
		return this.licenseName;
	}

	public void setLicenseName(String licenseName) {
		this.licenseName = licenseName;
	}

	public Set getEventLicenseMappings() {
		return this.eventLicenseMappings;
	}

	public void setEventLicenseMappings(Set eventLicenseMappings) {
		this.eventLicenseMappings = eventLicenseMappings;
	}

}
