package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private int paymentId;
	private String paymnetMode;
	private String chequeDd;
	private Date date;
	private String bankName;
	private Integer amount;
	private Integer total;
	private Integer balance;
	private Integer received;

	public Payment() {
	}

	public Payment(int paymentId, String bankName) {
		this.paymentId = paymentId;
		this.bankName = bankName;
	}

	public Payment(int paymentId, String paymnetMode, String chequeDd,
			Date date, String bankName, Integer amount, Integer total,
			Integer balance, Integer received) {
		this.paymentId = paymentId;
		this.paymnetMode = paymnetMode;
		this.chequeDd = chequeDd;
		this.date = date;
		this.bankName = bankName;
		this.amount = amount;
		this.total = total;
		this.balance = balance;
		this.received = received;
	}

	public int getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(int paymentId) {
		this.paymentId = paymentId;
	}

	public String getPaymnetMode() {
		return this.paymnetMode;
	}

	public void setPaymnetMode(String paymnetMode) {
		this.paymnetMode = paymnetMode;
	}

	public String getChequeDd() {
		return this.chequeDd;
	}

	public void setChequeDd(String chequeDd) {
		this.chequeDd = chequeDd;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public Integer getBalance() {
		return this.balance;
	}

	public void setBalance(Integer balance) {
		this.balance = balance;
	}

	public Integer getReceived() {
		return this.received;
	}

	public void setReceived(Integer received) {
		this.received = received;
	}

}
