package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

/**
 * RoleUserMappingId generated by hbm2java
 */
public class RoleUserMappingId implements java.io.Serializable {

	private int roleIdRoleId;
	private int userIdUserId;

	public RoleUserMappingId() {
	}

	public RoleUserMappingId(int roleIdRoleId, int userIdUserId) {
		this.roleIdRoleId = roleIdRoleId;
		this.userIdUserId = userIdUserId;
	}

	public int getRoleIdRoleId() {
		return this.roleIdRoleId;
	}

	public void setRoleIdRoleId(int roleIdRoleId) {
		this.roleIdRoleId = roleIdRoleId;
	}

	public int getUserIdUserId() {
		return this.userIdUserId;
	}

	public void setUserIdUserId(int userIdUserId) {
		this.userIdUserId = userIdUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleUserMappingId))
			return false;
		RoleUserMappingId castOther = (RoleUserMappingId) other;

		return (this.getRoleIdRoleId() == castOther.getRoleIdRoleId())
				&& (this.getUserIdUserId() == castOther.getUserIdUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleIdRoleId();
		result = 37 * result + this.getUserIdUserId();
		return result;
	}

}
