package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int roleId;
	private String roleName;
	private Set roleUserMappings = new HashSet(0);
	private Set userEventMappings = new HashSet(0);

	public Role() {
	}

	public Role(int roleId) {
		this.roleId = roleId;
	}

	public Role(int roleId, String roleName, Set roleUserMappings,
			Set userEventMappings) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleUserMappings = roleUserMappings;
		this.userEventMappings = userEventMappings;
	}

	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getRoleUserMappings() {
		return this.roleUserMappings;
	}

	public void setRoleUserMappings(Set roleUserMappings) {
		this.roleUserMappings = roleUserMappings;
	}

	public Set getUserEventMappings() {
		return this.userEventMappings;
	}

	public void setUserEventMappings(Set userEventMappings) {
		this.userEventMappings = userEventMappings;
	}

}
