package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int userId;
	private String userName;
	private String password;
	private String status;
	private Set roleUserMappings = new HashSet(0);

	public User() {
	}

	public User(int userId, String password) {
		this.userId = userId;
		this.password = password;
	}

	public User(int userId, String userName, String password, String status,
			Set roleUserMappings) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.status = status;
		this.roleUserMappings = roleUserMappings;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getRoleUserMappings() {
		return this.roleUserMappings;
	}

	public void setRoleUserMappings(Set roleUserMappings) {
		this.roleUserMappings = roleUserMappings;
	}

}
