package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

/**
 * UserEventMappingId generated by hbm2java
 */
public class UserEventMappingId implements java.io.Serializable {

	private int roleIdRoleId;
	private int eventIdEventId;

	public UserEventMappingId() {
	}

	public UserEventMappingId(int roleIdRoleId, int eventIdEventId) {
		this.roleIdRoleId = roleIdRoleId;
		this.eventIdEventId = eventIdEventId;
	}

	public int getRoleIdRoleId() {
		return this.roleIdRoleId;
	}

	public void setRoleIdRoleId(int roleIdRoleId) {
		this.roleIdRoleId = roleIdRoleId;
	}

	public int getEventIdEventId() {
		return this.eventIdEventId;
	}

	public void setEventIdEventId(int eventIdEventId) {
		this.eventIdEventId = eventIdEventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserEventMappingId))
			return false;
		UserEventMappingId castOther = (UserEventMappingId) other;

		return (this.getRoleIdRoleId() == castOther.getRoleIdRoleId())
				&& (this.getEventIdEventId() == castOther.getEventIdEventId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleIdRoleId();
		result = 37 * result + this.getEventIdEventId();
		return result;
	}

}
