package models;

// Generated 5 Apr, 2016 3:49:22 PM by Hibernate Tools 4.3.1

/**
 * UserEventMapping generated by hbm2java
 */
public class UserEventMapping implements java.io.Serializable {

	private UserEventMappingId id;
	private Event event;
	private Role role;

	public UserEventMapping() {
	}

	public UserEventMapping(UserEventMappingId id, Event event, Role role) {
		this.id = id;
		this.event = event;
		this.role = role;
	}

	public UserEventMappingId getId() {
		return this.id;
	}

	public void setId(UserEventMappingId id) {
		this.id = id;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
